version: '3'
services:
  aircraft-info-service:
    build: ./aircraft-info-service
    ports:
      - "8082:8080"


  aircraft-management-service:
    build: ./aircraft-management-service
    ports:
      - "8083:8080"

  api-service:
    build: ./api-service
    ports:
      - "8081:8080"

  flight-site-ui:
    build: ./flight-site-ui
    ports:
      - "80:80"